### PR TITLE
Add setup.py

### PR DESCRIPTION
**Pull request by stuaxo**
creates and entry point so you can run this as `cpp2python` in the shell

### CODE REVIEW

**Comment by andreikop** [comment]
Busy week. Will try to find some time soon

**Comment by stuaxo** [comment]
Cool - I was kind of guessing on the license, so I'd verify it's correct in setup.py before merging.

**Comment by andreikop** [comment]
Thanks!

I've made a few fixes and included you to the list of authors. I hope you don't mind.

**Comment by stuaxo** [comment]
No probs, cheers :)

**Pull request merged**
